# Use root/example as user/password credentials
version: '3.1'

services:
    python_app:
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            - compose-network
        volumes: 
            - "./src/:/home/"
        command:
            tail -f /dev/null

networks:
    compose-network:
        driver: bridge